# TCL File Generated by Component Editor 7.2 on:
# Fri Aug 08 16:33:32 CST 2008
# DO NOT MODIFY

set_source_file "Double_ADS805.v"
set_module "Double_ADS805"
set_module_description "1.0"
set_module_property "className" "Double_ADS805"
set_module_property "displayName" "Double_ADS805"
set_module_property "group" "sun"
set_module_property "synthesisFiles" [ list "Double_ADS805.v" "fifo.v" ]

# Module parameters

# Interface clock
add_interface "clock" "clock" "sink" "asynchronous"
# Ports in interface clock
add_port_to_interface "clock" "clk" "clk"
add_port_to_interface "clock" "rst_n" "reset_n"

# Interface export_0
add_interface "export_0" "conduit" "start" "asynchronous"
# Ports in interface export_0
add_port_to_interface "export_0" "ad_clk" "export"
add_port_to_interface "export_0" "i_input" "export"
add_port_to_interface "export_0" "u_input" "export"

# Interface avalon_slave_0
add_interface "avalon_slave_0" "avalon" "slave" "clock"
set_interface_property "avalon_slave_0" "isNonVolatileStorage" "false"
set_interface_property "avalon_slave_0" "burstOnBurstBoundariesOnly" "false"
set_interface_property "avalon_slave_0" "readLatency" "0"
set_interface_property "avalon_slave_0" "holdTime" "0"
set_interface_property "avalon_slave_0" "printableDevice" "false"
set_interface_property "avalon_slave_0" "readWaitTime" "1"
set_interface_property "avalon_slave_0" "setupTime" "0"
set_interface_property "avalon_slave_0" "addressAlignment" "DYNAMIC"
set_interface_property "avalon_slave_0" "writeWaitTime" "1"
set_interface_property "avalon_slave_0" "timingUnits" "Cycles"
set_interface_property "avalon_slave_0" "minimumUninterruptedRunLength" "1"
set_interface_property "avalon_slave_0" "isMemoryDevice" "false"
set_interface_property "avalon_slave_0" "linewrapBursts" "false"
set_interface_property "avalon_slave_0" "writeWaitStates" "1"
set_interface_property "avalon_slave_0" "maximumPendingReadTransactions" "0"
# Ports in interface avalon_slave_0
add_port_to_interface "avalon_slave_0" "write" "write"
add_port_to_interface "avalon_slave_0" "read" "read"
add_port_to_interface "avalon_slave_0" "readdata" "readdata"
add_port_to_interface "avalon_slave_0" "writedata" "writedata"
add_port_to_interface "avalon_slave_0" "address" "address"

# Interface Avalon_Slave_0_irq
add_interface "Avalon_Slave_0_irq" "interrupt" "sender" "clock"
set_interface_property "Avalon_Slave_0_irq" "associatedAddressablePoint" "avalon_slave_0"
# Ports in interface Avalon_Slave_0_irq
add_port_to_interface "Avalon_Slave_0_irq" "irq" "irq"
